fix: download correct rc or ga release
tidev/titanium pull request #580
Opened 2022-05-23 20:49 UTC by caspahouzer

This PR fixes the download of the correct RC or GA version of the SDK.

To test, just try
`ti sdk install latest`
`ti sdk install 11.0.0.RC`
`ti sdk install 10.1.1.GA`

If you have already installed a version use `--force`

Big kudos to **Bruno**, which make this PR possible

2022-05-23 20:55 UTC, ecarruda approved these changes

2022-05-23 21:35 UTC, ecarruda commented on lib/commands/sdk.js
> +				const [ , versionType, assetOS ] = osRegex.exec(asset.name);
```suggestion
				const [ , , assetOS ] = osRegex.exec(asset.name);
```
versionType is not used.

2022-05-23 21:35 UTC, ecarruda commented on lib/commands/sdk.js
> +				name = !versionType || !dot ? `${version}.GA` : `${version}.${versionType}`;
```suggestion
				if (!version || !versionType || !dot) {
					name = name.includes('GA') ? name : `${name}.GA`;
				} else {
					name = `${version}.${versionType}`;
				}
```

Why not let as fallback the old code propose?

2022-05-23 21:37 UTC, ecarruda commented
I created this issue and was going to publish my PR when i saw your PR linking my issue, just some ideas about what I did on my branch.

2022-05-23 21:39 UTC, ecarruda requested changes

2022-05-23 21:39 UTC, ecarruda commented on lib/commands/sdk.js
> +				name = !versionType || !dot ? `${version}.GA` : `${version}.${versionType}`;
This is just an idea because RC is always o the name (at least until now).

2022-05-23 21:40 UTC, ecarruda requested changes

2022-05-23 21:40 UTC, ecarruda commented on lib/commands/sdk.js
> +				const [ , versionType, assetOS ] = osRegex.exec(asset.name);
```suggestion
				const [ , , assetOS ] = osRegex.exec(asset.name);
```

versionType is not used

2022-05-24 05:05 UTC, caspahouzer commented
```
ti sdk install 11.0.0.RC
Titanium SDK 11.0.0.RC is already installed!

ti sdk install latest
You're up-to-date. Version 10.1.1.GA is currently the newest version available.
```

2022-05-24 07:22 UTC, caspahouzer commented
Closing this PR in favour of https://github.com/tidev/titanium/pull/583

2022-05-24 07:22 UTC, closed without merging